---
# tasks file for kube-slave
  - name: "Install Docker"
    package:
      name: "docker"

  - name: "Start Docker services"
    service:
      name: "docker"
      enabled: yes
      state: started
   
  - name: "Creating kubeadm yum repo" 
    yum_repository:
      name: "kubernetes"
      description: "k8s repo"
      baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch'
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: "Install kubeadm"
    package:
      name: kubeadm
  
  - name: "Start kubelet services"
    service:
      name: "kubelet"
      enabled: yes
      state: started

  - name: "Creating docker config file"
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
               {
               "exec-opts": ["native.cgroupdriver=systemd"]
               }

  - name: "Restart Docker services"
    service:
      name: "docker"
      state: restarted

  - name: "Install iproute-tc"
    package:
      name: "iproute-tc"

  - name: "iproute"
    copy:
      dest: "/etc/sysctl.d/k8s.conf"
      content: |
             net.bridge.bridge-nf-call-ip6tables = 1
             net.bridge.bridge-nf-call-iptables = 1

  - shell: "sysctl --system"

  - name: "Joining the worker node"
    command: "{{ join_cmd }}"
    ignore_errors: yes

