---
# tasks file for webserver
- include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      files:
      - "../vars/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"

- name: "Installing HTTPD and PHP"
  package: 
    name: "{{ item }}"
    state: present
  loop:
  - "{{ pkg_name }}"
  - "php"

- name: "Copying the static file/webpage"
  copy:
    src: "index.php" 
    dest: "/var/www/html"

- name: "Starting the webserver services"
  service:
    name: "{{ service }}"
    state: started

- name: "Creating rule for 80/tcp in firewall"
  firewalld:
    port: "80/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  ignore_errors: yes
